baseURL = "https://corwink2021.netlify.app/"
languageCode = "en-us"
[[menu.main]]
name = "Shop"
weight = 5
url = "/products"
[[menu.main]]
name = "Tutorials"
url = "/categories/tutorial"
weight = 4
[[menu.main]]
name = "Videos"
weight = 3
url = "/videos"
[[menu.main]]
name = "Contact"
weight = 8
url = "/contact"
[[menu.main]]
name = "Home"
url = "/"
weight = 1
[outputs]
home = ["HTML", "RSS", "JSON"]
[taxonomies]
category = "categories"
eyeliner = "eyeliners"
lash-material = "lash-materials"
lash-type = "lash-types"
tag = "tags"
collection = "collections"